{{- if .Values.ingress.enabled -}}
{{- $name := include "app.name"  . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{ include "app.metadataLabels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ include "app.metadataAnnotations" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ .host | quote }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $name }}-flask
              servicePort: 5000
        {{- end }}
  {{- end }}
{{- end }}
