replicas: 1
image:
  name: eu.gcr.io/practica-vms/keepcoding/flask-kubernetes
  tag: latest
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: practica.34.78.37.87.nip.io
      paths:
      - "/"

redis:
  cluster:
    enabled: false
